version: '3.7'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce 
    restart: always
    volumes:
      - './data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`${PORTAINER_HOST}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certResolver=namecheap"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"